import Head from 'next/head'
import Image from 'next/image'
import Navbar from "../component/Landing/Navbar";
import HeroLanding from "../component/Landing/HeroLanding"
import Me from '../component/Landing/Me';
import Content from '../component/Landing/content';

export default function Home() {
  return (
    <div >
        <Head>
          <title>Desta Muttaqin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          
          </Head>
        <Navbar/>
        <HeroLanding/>
        <Me/>
        {/* <Content/> */}
     
   
    </div>
  )
}
